### ISSUE TITLE
Exception in Olo questions

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#6]
```
05-17 15:10:46.773 16149-16149/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.aware.plugin.hyks, PID: 16149
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.widget.RadioButton.getText()' on a null object reference
                                                       at com.aware.plugin.hyks.olo$6.onClick(olo.java:240)
                                                       at android.view.View.performClick(View.java:5204)
                                                       at android.view.View$PerformClick.run(View.java:21153)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by rkdarst** [comment]
It seems the one right above could be tested to see if the ID is `-1`.  I just added this:

```
                        int radio_button_olo4_7_1 = olo4_7_1_radio_group.getCheckedRadioButtonId(); //if -1, no radio button was checked
                        if (radio_button_olo4_7_1 == -1) {
                            Toast toast = Toast.makeText(getApplicationContext(), warning, Toast.LENGTH_SHORT);
                            toast.show();
                            return;
                        }
                        String olo4_7_1_radio_group_answer = String.valueOf(((RadioButton) findViewById(radio_button_olo4_7_1)).getText());
```

Do you think this works?  Added to my running PR.
