### ISSUE TITLE
Must restart phone before you can do the first PHQ9

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#7]
@AnaTomomi reports:

If you join a study, it will show PHQ9 right away.  If you try clicking on it then, it won't show anything.  The workaround is to restart the phone before clicking on the PHQ9 notification.

I'll investigate tonight.

**Comment by rkdarst** [comment]
```
05-18 04:57:44.187 7806-7806/com.aware.plugin.hyks D/AndroidRuntime: Shutting down VM
05-18 04:57:44.193 7806-7806/com.aware.plugin.hyks E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.aware.plugin.hyks, PID: 7806
                                                                     java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.aware.plugin.hyks/com.aware.plugin.hyks.phq9}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                         at android.content.ContextWrapper.getResources(ContextWrapper.java:87)
                                                                         at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:81)
                                                                         at android.content.Context.getString(Context.java:409)
                                                                         at com.aware.plugin.hyks.phq9.<init>(phq9.java:27)
                                                                         at java.lang.Class.newInstance(Native Method)
                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by rkdarst** [comment]
I at least fixed that one above... however I only get one PHQ9 at the beginning.  Is that how it should be?

**Comment by AnaTomomi** [comment]
Two comments: 
1. The issue is not only for PHQ9, it is for all questionnaires. So even OLO will not show if some phones are not reset. 
2. Depends on the time range... You should get a PHQ9 when you join the study. Then, PHQ9 will appear every 2 weeks.

**Comment by rkdarst** [comment]
Oh... well, at least I was able to do PHQ9 right away now.  Can you
try to reproduce with latest (latest is a5caf59 from my repo)?  I'm at
least able to do PHQ9 on my phone right away now.

Could be android related again...

**Comment by AnaTomomi** [comment]
Problem still persists on Samsung Mega. Android version 4.4.2

**Comment by AnaTomomi** [comment]
Problem solved. The issue can be closed
